apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cast-website.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cast-website.name" . }}
    helm.sh/chart: {{ include "cast-website.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cast-website.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cast-website.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: {{ .Values.container.protocol }}
          env:
            - name: NODE_ENV
              value: "production"

            - name: REACT_APP_GET_IDENTITY_PATH
              value: {{ .Values.paths.identity | quote }}
            - name: REACT_APP_TWITTER_LOGIN_PATH
              value: {{ .Values.paths.twitter | quote }}
            - name: REACT_APP_POST_PATH
              value: {{ .Values.paths.post | quote }}

          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
