# Default values for cast-render.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/multipl/cast-render
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []

root_url: https://cast.multipl.io

environment:
  NAME: render

  DPI: 72
  FONTFILE: fonts/NotoSans-Regular.ttf

  POST_TEMPLATE: templates/post.mustache

ipfs_address: cast-ipfs-ipfs:5001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
