# Default values for multipl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/multipl/website
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7000

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
