---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cast-ipfs
  namespace: multipl
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: cast-ipfs
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: ipfs
    version: 0.2.2
  values:
    image: ipfs/go-ipfs:v0.4.20
