---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cast-render
  namespace: multipl
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: cast-render
  chart:
    git: ssh://git@github.com/multiplio/DEPLOY
    ref: master
    path: charts/cast/cast-render
  values:
    image:
      repository: gcr.io/multipl/cast-render
      tag: stable
      pullPolicy: IfNotPresent
