---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cast-user
  namespace: multipl
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
    flux.weave.works/tag.mailgun: semver:~1
spec:
  releaseName: cast-user
  chart:
    git: ssh://git@github.com/multiplio/DEPLOY
    ref: master
    path: charts/cast/cast-user
  values:
    image:
      repository: gcr.io/multipl/cast-user
      tag: 1.1.4
      pullPolicy: IfNotPresent
    mailgun:
      image:
        repository: gcr.io/multipl/mailgun
        tag: 1.2.1
        pullPolicy: IfNotPresent
