# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

container:
  port: 80

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
