apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: multipl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - multipl.io
    - www.multipl.io
    - cast.multipl.io
    secretName: letsencrypt-production
  rules:
  - host: multipl.io
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 7000
  - host: cast.multipl.io
    http:
      paths:
      - path: /identity
          serviceName: cast-user
          servicePort: 7000
      - path: /auth/twitter
          serviceName: cast-user
          servicePort: 7000
      - path: /auth/twitter/callback
          serviceName: cast-user
          servicePort: 7000
      - path: /logout
          serviceName: cast-user
          servicePort: 7000
      - backend:
          serviceName: cast-website
          servicePort: 7000
