apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "cast-render.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cast-render.name" . }}
    helm.sh/chart: {{ include "cast-render.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cast-render.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cast-render.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: main
              containerPort: 3000
              protocol: TCP
          env:
            - name: NAME
              value: {{ .Values.environment.NAME | quote }}
            - name: ADDRESS
              value: ":3000"

            - name: DPI
              value: {{ .Values.environment.DPI | quote }}
            - name: FONTFILE
              value: {{ .Values.environment.FONTFILE | quote }}

            - name: POST_TEMPLATE
              value: {{ .Values.environment.POST_TEMPLATE | quote }}
            - name: ROOT_URL
              value: {{ .Values.root_url | quote }}

            - name: IPFS_ADDRESS
              value: {{ .Values.ipfs_address | quote }}

          readinessProbe:
            httpGet:
              path: /ready
              port: main
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
