apiVersion: v1
kind: Service
metadata:
  name: {{ include "cast-publish.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cast-publish.name" . }}
    helm.sh/chart: {{ include "cast-publish.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: main
  selector:
    app.kubernetes.io/name: {{ include "cast-publish.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
