# Default values for cast-user.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/multipl/cast-user
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

environment:
  NODE_ENV: production
  PROGRAM_ALIAS: login

  #level=debug|info
  LOG_LEVEL: debug

mailgun_address: cast-user-mailgun:8000

db_address: cast-db-users-mongodb:27017

secret:
  cookie: cast-cookie
  twitter: cast-twitter
  db_password: cast-db-users-mongodb

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mailgun:
  replicaCount: 1
  image:
    repository: gcr.io/multipl/mailgun
    tag: stable
    pullPolicy: IfNotPresent
