---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: website
  namespace: multipl
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.0.*
spec:
  releaseName: website
  chart:
    git: ssh://git@github.com/multipl/DEPLOY
    ref: master
    path: charts/website
  values:
    image:
      tag: latest
