---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: website
  namespace: multipl
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: website
  chart:
    git: ssh://git@github.com/multiplio/DEPLOY
    ref: master
    path: charts/website
  values:
    image:
      repository: gcr.io/multipl/website
      tag: c0ae2e8d5443107ae2e0c08eb4674caff7c30fe9
      pullPolicy: IfNotPresent
    serviceType: ClusterIP
