apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cast-user.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cast-user.name" . }}
    helm.sh/chart: {{ include "cast-user.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cast-user.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cast-user.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: main
              containerPort: 7000
              protocol: TCP
          env:
            - name: PROGRAM_ALIAS
              valueFrom:
                configMapKeyRef:
                  key: PROGRAM_ALIAS
                  name: {{ include "cast-user.fullname" . }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: {{ include "cast-user.fullname" . }}
            - name: PORT
              value: 7000

            - name: LOG_FILE
              value: false
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: {{ include "cast-user.fullname" . }}

            - name: EMAILER_ADDRESS
              value: {{ .Values.mailgun_address | quote }}

            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.cookie | quote }}
                  key: value

            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.twitter | quote }}
                  key: consumer-key
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.twitter | quote }}
                  key: consumer-secret
            - name: TWITTER_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.twitter | quote }}
                  key: callback

            - name: DATABASE_NAME
              value: users
            - name: DATABASE_PROTOCOL
              value: mongodb
            - name: DATABASE_ADDRESS
              value: {{ .Values.db_address }}
            - name: DATABASE_OPTIONS
              value: "authSource=admin"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.db_password | quote }}
                  key: mongodb-root-password

          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
