apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailgun.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mailgun.name" . }}
    helm.sh/chart: {{ include "mailgun.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  PROGRAM_ALIAS: {{ .Values.environment.PROGRAM_ALIAS | quote }}
  NODE_ENV: {{ .Values.environment.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.environment.LOG_LEVEL | quote }}
