apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailgun.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mailgun.name" . }}
    helm.sh/chart: {{ include "mailgun.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mailgun.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mailgun.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: main
              containerPort: 3000
              protocol: TCP
          env:
            - name: PROGRAM_ALIAS
              valueFrom:
                configMapKeyRef:
                  key: PROGRAM_ALIAS
                  name: {{ include "mailgun.fullname" . }}
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: {{ include "mailgun.fullname" . }}
            - name: PORT
              value: 3000

            - name: LOG_FILE
              value: false
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: {{ include "mailgun.fullname" . }}

            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: api-key
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret | quote }}
                  key: domain

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
