# Default values for cast-publish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/multipl/cast-publish
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

environment:
  PROGRAM_ALIAS: publish
  # base url of posts (for linking)
  POST_URL: https://cast.multipl.io/post/

db_address: cast-db-users-mongodb:27017

secret:
  twitter: cast-twitter
  db_password: cast-db-users-mongodb

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
